export const speciesItems = [
  { label: "Cachorro", value: "dog" },
  { label: "Gato", value: "cat" },
  { label: "Ave", value: "bird" },
  { label: "Coelho", value: "rabbit" },
  { label: "Hamster", value: "hamster" },
  { label: "Porquinho-da-Índia", value: "guinea_pig" },
  { label: "Furão", value: "ferret" },
  { label: "Cavalo", value: "horse" },
  { label: "Vaca", value: "cow" },
  { label: "Cabra", value: "goat" },
  { label: "Ovelha", value: "sheep" },
  { label: "Porco", value: "pig" },
  { label: "Peixe", value: "fish" },
  { label: "Tartaruga", value: "turtle" },
  { label: "Jabuti", value: "tortoise" },
  { label: "Cobra", value: "snake" },
  { label: "Lagarto", value: "lizard" },
  { label: "Papagaio", value: "parrot" },
  { label: "Calopsita", value: "cockatiel" },
  { label: "Periquito", value: "budgerigar" },
  { label: "Chinchila", value: "chinchilla" },
  { label: "Ouriço", value: "hedgehog" },
  { label: "Outro", value: "other" },
];
