/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPetsIndexRouteImport } from './routes/_authenticated/pets/index'
import { Route as AuthenticatedOwnersIndexRouteImport } from './routes/_authenticated/owners/index'
import { Route as AuthenticatedPetsCreateRouteImport } from './routes/_authenticated/pets/create'
import { Route as AuthenticatedOwnersCreateRouteImport } from './routes/_authenticated/owners/create'
import { Route as AuthenticatedOwnersIdIndexRouteImport } from './routes/_authenticated/owners/$id/index'
import { Route as AuthenticatedOwnersIdEditRouteImport } from './routes/_authenticated/owners/$id/edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPetsIndexRoute = AuthenticatedPetsIndexRouteImport.update({
  id: '/pets/',
  path: '/pets/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOwnersIndexRoute =
  AuthenticatedOwnersIndexRouteImport.update({
    id: '/owners/',
    path: '/owners/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPetsCreateRoute = AuthenticatedPetsCreateRouteImport.update({
  id: '/pets/create',
  path: '/pets/create',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOwnersCreateRoute =
  AuthenticatedOwnersCreateRouteImport.update({
    id: '/owners/create',
    path: '/owners/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnersIdIndexRoute =
  AuthenticatedOwnersIdIndexRouteImport.update({
    id: '/owners/$id/',
    path: '/owners/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnersIdEditRoute =
  AuthenticatedOwnersIdEditRouteImport.update({
    id: '/owners/$id/edit',
    path: '/owners/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/owners/create': typeof AuthenticatedOwnersCreateRoute
  '/pets/create': typeof AuthenticatedPetsCreateRoute
  '/owners/': typeof AuthenticatedOwnersIndexRoute
  '/pets/': typeof AuthenticatedPetsIndexRoute
  '/owners/$id/edit': typeof AuthenticatedOwnersIdEditRoute
  '/owners/$id/': typeof AuthenticatedOwnersIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/owners/create': typeof AuthenticatedOwnersCreateRoute
  '/pets/create': typeof AuthenticatedPetsCreateRoute
  '/owners': typeof AuthenticatedOwnersIndexRoute
  '/pets': typeof AuthenticatedPetsIndexRoute
  '/owners/$id/edit': typeof AuthenticatedOwnersIdEditRoute
  '/owners/$id': typeof AuthenticatedOwnersIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/owners/create': typeof AuthenticatedOwnersCreateRoute
  '/_authenticated/pets/create': typeof AuthenticatedPetsCreateRoute
  '/_authenticated/owners/': typeof AuthenticatedOwnersIndexRoute
  '/_authenticated/pets/': typeof AuthenticatedPetsIndexRoute
  '/_authenticated/owners/$id/edit': typeof AuthenticatedOwnersIdEditRoute
  '/_authenticated/owners/$id/': typeof AuthenticatedOwnersIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/owners/create'
    | '/pets/create'
    | '/owners/'
    | '/pets/'
    | '/owners/$id/edit'
    | '/owners/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/owners/create'
    | '/pets/create'
    | '/owners'
    | '/pets'
    | '/owners/$id/edit'
    | '/owners/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/owners/create'
    | '/_authenticated/pets/create'
    | '/_authenticated/owners/'
    | '/_authenticated/pets/'
    | '/_authenticated/owners/$id/edit'
    | '/_authenticated/owners/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pets/': {
      id: '/_authenticated/pets/'
      path: '/pets'
      fullPath: '/pets/'
      preLoaderRoute: typeof AuthenticatedPetsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owners/': {
      id: '/_authenticated/owners/'
      path: '/owners'
      fullPath: '/owners/'
      preLoaderRoute: typeof AuthenticatedOwnersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pets/create': {
      id: '/_authenticated/pets/create'
      path: '/pets/create'
      fullPath: '/pets/create'
      preLoaderRoute: typeof AuthenticatedPetsCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owners/create': {
      id: '/_authenticated/owners/create'
      path: '/owners/create'
      fullPath: '/owners/create'
      preLoaderRoute: typeof AuthenticatedOwnersCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owners/$id/': {
      id: '/_authenticated/owners/$id/'
      path: '/owners/$id'
      fullPath: '/owners/$id/'
      preLoaderRoute: typeof AuthenticatedOwnersIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owners/$id/edit': {
      id: '/_authenticated/owners/$id/edit'
      path: '/owners/$id/edit'
      fullPath: '/owners/$id/edit'
      preLoaderRoute: typeof AuthenticatedOwnersIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOwnersCreateRoute: typeof AuthenticatedOwnersCreateRoute
  AuthenticatedPetsCreateRoute: typeof AuthenticatedPetsCreateRoute
  AuthenticatedOwnersIndexRoute: typeof AuthenticatedOwnersIndexRoute
  AuthenticatedPetsIndexRoute: typeof AuthenticatedPetsIndexRoute
  AuthenticatedOwnersIdEditRoute: typeof AuthenticatedOwnersIdEditRoute
  AuthenticatedOwnersIdIndexRoute: typeof AuthenticatedOwnersIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOwnersCreateRoute: AuthenticatedOwnersCreateRoute,
  AuthenticatedPetsCreateRoute: AuthenticatedPetsCreateRoute,
  AuthenticatedOwnersIndexRoute: AuthenticatedOwnersIndexRoute,
  AuthenticatedPetsIndexRoute: AuthenticatedPetsIndexRoute,
  AuthenticatedOwnersIdEditRoute: AuthenticatedOwnersIdEditRoute,
  AuthenticatedOwnersIdIndexRoute: AuthenticatedOwnersIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
