/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedPetsIndexRouteImport } from './routes/_authenticated/pets/index'
import { Route as AuthenticatedOwnersIndexRouteImport } from './routes/_authenticated/owners/index'
import { Route as AuthenticatedAppointmentsIndexRouteImport } from './routes/_authenticated/appointments/index'
import { Route as AuthenticatedUsersCreateRouteImport } from './routes/_authenticated/users/create'
import { Route as AuthenticatedPetsCreateRouteImport } from './routes/_authenticated/pets/create'
import { Route as AuthenticatedOwnersCreateRouteImport } from './routes/_authenticated/owners/create'
import { Route as AuthenticatedUsersIdIndexRouteImport } from './routes/_authenticated/users/$id/index'
import { Route as AuthenticatedPetsIdIndexRouteImport } from './routes/_authenticated/pets/$id/index'
import { Route as AuthenticatedOwnersIdIndexRouteImport } from './routes/_authenticated/owners/$id/index'
import { Route as AuthenticatedUsersIdEditRouteImport } from './routes/_authenticated/users/$id/edit'
import { Route as AuthenticatedPetsIdEditRouteImport } from './routes/_authenticated/pets/$id/edit'
import { Route as AuthenticatedOwnersIdEditRouteImport } from './routes/_authenticated/owners/$id/edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPetsIndexRoute = AuthenticatedPetsIndexRouteImport.update({
  id: '/pets/',
  path: '/pets/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOwnersIndexRoute =
  AuthenticatedOwnersIndexRouteImport.update({
    id: '/owners/',
    path: '/owners/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppointmentsIndexRoute =
  AuthenticatedAppointmentsIndexRouteImport.update({
    id: '/appointments/',
    path: '/appointments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersCreateRoute =
  AuthenticatedUsersCreateRouteImport.update({
    id: '/users/create',
    path: '/users/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPetsCreateRoute = AuthenticatedPetsCreateRouteImport.update({
  id: '/pets/create',
  path: '/pets/create',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOwnersCreateRoute =
  AuthenticatedOwnersCreateRouteImport.update({
    id: '/owners/create',
    path: '/owners/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIdIndexRoute =
  AuthenticatedUsersIdIndexRouteImport.update({
    id: '/users/$id/',
    path: '/users/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPetsIdIndexRoute =
  AuthenticatedPetsIdIndexRouteImport.update({
    id: '/pets/$id/',
    path: '/pets/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnersIdIndexRoute =
  AuthenticatedOwnersIdIndexRouteImport.update({
    id: '/owners/$id/',
    path: '/owners/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIdEditRoute =
  AuthenticatedUsersIdEditRouteImport.update({
    id: '/users/$id/edit',
    path: '/users/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPetsIdEditRoute = AuthenticatedPetsIdEditRouteImport.update({
  id: '/pets/$id/edit',
  path: '/pets/$id/edit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOwnersIdEditRoute =
  AuthenticatedOwnersIdEditRouteImport.update({
    id: '/owners/$id/edit',
    path: '/owners/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/owners/create': typeof AuthenticatedOwnersCreateRoute
  '/pets/create': typeof AuthenticatedPetsCreateRoute
  '/users/create': typeof AuthenticatedUsersCreateRoute
  '/appointments/': typeof AuthenticatedAppointmentsIndexRoute
  '/owners/': typeof AuthenticatedOwnersIndexRoute
  '/pets/': typeof AuthenticatedPetsIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/owners/$id/edit': typeof AuthenticatedOwnersIdEditRoute
  '/pets/$id/edit': typeof AuthenticatedPetsIdEditRoute
  '/users/$id/edit': typeof AuthenticatedUsersIdEditRoute
  '/owners/$id/': typeof AuthenticatedOwnersIdIndexRoute
  '/pets/$id/': typeof AuthenticatedPetsIdIndexRoute
  '/users/$id/': typeof AuthenticatedUsersIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/owners/create': typeof AuthenticatedOwnersCreateRoute
  '/pets/create': typeof AuthenticatedPetsCreateRoute
  '/users/create': typeof AuthenticatedUsersCreateRoute
  '/appointments': typeof AuthenticatedAppointmentsIndexRoute
  '/owners': typeof AuthenticatedOwnersIndexRoute
  '/pets': typeof AuthenticatedPetsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/owners/$id/edit': typeof AuthenticatedOwnersIdEditRoute
  '/pets/$id/edit': typeof AuthenticatedPetsIdEditRoute
  '/users/$id/edit': typeof AuthenticatedUsersIdEditRoute
  '/owners/$id': typeof AuthenticatedOwnersIdIndexRoute
  '/pets/$id': typeof AuthenticatedPetsIdIndexRoute
  '/users/$id': typeof AuthenticatedUsersIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/owners/create': typeof AuthenticatedOwnersCreateRoute
  '/_authenticated/pets/create': typeof AuthenticatedPetsCreateRoute
  '/_authenticated/users/create': typeof AuthenticatedUsersCreateRoute
  '/_authenticated/appointments/': typeof AuthenticatedAppointmentsIndexRoute
  '/_authenticated/owners/': typeof AuthenticatedOwnersIndexRoute
  '/_authenticated/pets/': typeof AuthenticatedPetsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/owners/$id/edit': typeof AuthenticatedOwnersIdEditRoute
  '/_authenticated/pets/$id/edit': typeof AuthenticatedPetsIdEditRoute
  '/_authenticated/users/$id/edit': typeof AuthenticatedUsersIdEditRoute
  '/_authenticated/owners/$id/': typeof AuthenticatedOwnersIdIndexRoute
  '/_authenticated/pets/$id/': typeof AuthenticatedPetsIdIndexRoute
  '/_authenticated/users/$id/': typeof AuthenticatedUsersIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/owners/create'
    | '/pets/create'
    | '/users/create'
    | '/appointments/'
    | '/owners/'
    | '/pets/'
    | '/users/'
    | '/owners/$id/edit'
    | '/pets/$id/edit'
    | '/users/$id/edit'
    | '/owners/$id/'
    | '/pets/$id/'
    | '/users/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/owners/create'
    | '/pets/create'
    | '/users/create'
    | '/appointments'
    | '/owners'
    | '/pets'
    | '/users'
    | '/owners/$id/edit'
    | '/pets/$id/edit'
    | '/users/$id/edit'
    | '/owners/$id'
    | '/pets/$id'
    | '/users/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/owners/create'
    | '/_authenticated/pets/create'
    | '/_authenticated/users/create'
    | '/_authenticated/appointments/'
    | '/_authenticated/owners/'
    | '/_authenticated/pets/'
    | '/_authenticated/users/'
    | '/_authenticated/owners/$id/edit'
    | '/_authenticated/pets/$id/edit'
    | '/_authenticated/users/$id/edit'
    | '/_authenticated/owners/$id/'
    | '/_authenticated/pets/$id/'
    | '/_authenticated/users/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pets/': {
      id: '/_authenticated/pets/'
      path: '/pets'
      fullPath: '/pets/'
      preLoaderRoute: typeof AuthenticatedPetsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owners/': {
      id: '/_authenticated/owners/'
      path: '/owners'
      fullPath: '/owners/'
      preLoaderRoute: typeof AuthenticatedOwnersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/appointments/': {
      id: '/_authenticated/appointments/'
      path: '/appointments'
      fullPath: '/appointments/'
      preLoaderRoute: typeof AuthenticatedAppointmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/create': {
      id: '/_authenticated/users/create'
      path: '/users/create'
      fullPath: '/users/create'
      preLoaderRoute: typeof AuthenticatedUsersCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pets/create': {
      id: '/_authenticated/pets/create'
      path: '/pets/create'
      fullPath: '/pets/create'
      preLoaderRoute: typeof AuthenticatedPetsCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owners/create': {
      id: '/_authenticated/owners/create'
      path: '/owners/create'
      fullPath: '/owners/create'
      preLoaderRoute: typeof AuthenticatedOwnersCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/$id/': {
      id: '/_authenticated/users/$id/'
      path: '/users/$id'
      fullPath: '/users/$id/'
      preLoaderRoute: typeof AuthenticatedUsersIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pets/$id/': {
      id: '/_authenticated/pets/$id/'
      path: '/pets/$id'
      fullPath: '/pets/$id/'
      preLoaderRoute: typeof AuthenticatedPetsIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owners/$id/': {
      id: '/_authenticated/owners/$id/'
      path: '/owners/$id'
      fullPath: '/owners/$id/'
      preLoaderRoute: typeof AuthenticatedOwnersIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/$id/edit': {
      id: '/_authenticated/users/$id/edit'
      path: '/users/$id/edit'
      fullPath: '/users/$id/edit'
      preLoaderRoute: typeof AuthenticatedUsersIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pets/$id/edit': {
      id: '/_authenticated/pets/$id/edit'
      path: '/pets/$id/edit'
      fullPath: '/pets/$id/edit'
      preLoaderRoute: typeof AuthenticatedPetsIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owners/$id/edit': {
      id: '/_authenticated/owners/$id/edit'
      path: '/owners/$id/edit'
      fullPath: '/owners/$id/edit'
      preLoaderRoute: typeof AuthenticatedOwnersIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOwnersCreateRoute: typeof AuthenticatedOwnersCreateRoute
  AuthenticatedPetsCreateRoute: typeof AuthenticatedPetsCreateRoute
  AuthenticatedUsersCreateRoute: typeof AuthenticatedUsersCreateRoute
  AuthenticatedAppointmentsIndexRoute: typeof AuthenticatedAppointmentsIndexRoute
  AuthenticatedOwnersIndexRoute: typeof AuthenticatedOwnersIndexRoute
  AuthenticatedPetsIndexRoute: typeof AuthenticatedPetsIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedOwnersIdEditRoute: typeof AuthenticatedOwnersIdEditRoute
  AuthenticatedPetsIdEditRoute: typeof AuthenticatedPetsIdEditRoute
  AuthenticatedUsersIdEditRoute: typeof AuthenticatedUsersIdEditRoute
  AuthenticatedOwnersIdIndexRoute: typeof AuthenticatedOwnersIdIndexRoute
  AuthenticatedPetsIdIndexRoute: typeof AuthenticatedPetsIdIndexRoute
  AuthenticatedUsersIdIndexRoute: typeof AuthenticatedUsersIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOwnersCreateRoute: AuthenticatedOwnersCreateRoute,
  AuthenticatedPetsCreateRoute: AuthenticatedPetsCreateRoute,
  AuthenticatedUsersCreateRoute: AuthenticatedUsersCreateRoute,
  AuthenticatedAppointmentsIndexRoute: AuthenticatedAppointmentsIndexRoute,
  AuthenticatedOwnersIndexRoute: AuthenticatedOwnersIndexRoute,
  AuthenticatedPetsIndexRoute: AuthenticatedPetsIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedOwnersIdEditRoute: AuthenticatedOwnersIdEditRoute,
  AuthenticatedPetsIdEditRoute: AuthenticatedPetsIdEditRoute,
  AuthenticatedUsersIdEditRoute: AuthenticatedUsersIdEditRoute,
  AuthenticatedOwnersIdIndexRoute: AuthenticatedOwnersIdIndexRoute,
  AuthenticatedPetsIdIndexRoute: AuthenticatedPetsIdIndexRoute,
  AuthenticatedUsersIdIndexRoute: AuthenticatedUsersIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
